/* For Query */
export const CHANGE_TODO_STATUS = "CHANGE_TODO_STATUS";
export const CHANGE_PREV_TODO_STATUS = "CHANGE_PREV_TODO_STATUS";
export const CHANGE_TODO_ID_Of_CLICKED_UPDATE_BUTTON =
  "CHANGE_TODO_ID_Of_CLICKED_UPDATE_BUTTON";
export const GET_TODOS = "GET_TODOS";
export const CHANGE_GET_TODOS_QUERY_VARIABLES =
  "CHANGE_GET_TODOS_QUERY_VARIABLES";

/* For Mutation */
export const MAKE_TODO = "MAKE_TODO";
export const UPDATE_TODO_DESCRIPTION = "UPDATE_TODO_DESCRIPTION";
